services:
  apps:
    image: ${DOCKER_BASE}
    build:
      context: .
      args:
        ENV_FILE: ${ENV_FILE}
    env_file: ${ENV_FILE}
    command: "gunicorn wsgi --preload -b :8000 --threads=10 --workers=4 --timeout=60 --max-requests=1000 --log-level 'warn'" 
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT}:8000"

